<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-YetAnotherLeagueStatTracker-f271cbbe-b045-489e-b546-5983e5d7773b</UserSecretsId>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Apis.Auth.AspNetCore3" Version="1.75.0" />
        <PackageReference Include="Microting.EntityFrameworkCore.MySql" Version="10.0.10" />
        <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="3.0.0" />
        <ProjectReference Include="..\YetAnotherLeagueStatTracker.Client\YetAnotherLeagueStatTracker.Client.csproj"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\Migrations\" />
      <Folder Include="wwwroot\js\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\GameAugment.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\GameParticipant.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\GameParticipants.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\GameSpell.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\MatchHistoryGame.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\MatchItem.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\SmallProfilePicture.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\Subteam.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Profile\Game\Team.razor" />
    </ItemGroup>

</Project>
